Repository capacitor-community/keep-awake, pull requests merged in 2021-04, with the labels that each got.

#7 feat: add support for Capacitor 3
  CapacitorCommunityKeepAwake.podspec
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  android/src/main/java/com/getcapacitor/community/keepawake/KeepAwake.java
  ios/Plugin.xcodeproj/project.pbxproj
  ios/Podfile
  package-lock.json
  package.json
  rollup.config.js
  src/definitions.ts
  src/index.ts
  src/web.ts
  tsconfig.json
Labels: breaking change, feature

#8 refactor: apply capacitor 3 plugin template
  .eslintignore
  .github/workflows/ci.yml
  .github/workflows/main.yml
  .gitignore
  .npmrc
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  android/.gitignore
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  android/src/main/AndroidManifest.xml
  android/src/main/java/com/getcapacitor/community/keepawake/KeepAwakePlugin.java
  android/src/main/res/.gitkeep
  android/src/main/res/layout/bridge_layout_main.xml
  android/src/main/res/values/colors.xml
  android/src/main/res/values/strings.xml
  android/src/main/res/values/styles.xml
  ios/Plugin.xcodeproj/project.pbxproj
  ios/Plugin.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  ios/Plugin.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/Plugin.xcodeproj/xcshareddata/xcschemes/Plugin.xcscheme
  ios/Plugin.xcodeproj/xcshareddata/xcschemes/PluginTests.xcscheme
  ios/Plugin.xcworkspace/contents.xcworkspacedata
  ios/Plugin.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/Plugin/KeepAwakePlugin.h
  ios/Plugin/KeepAwakePlugin.m
  ios/Plugin/KeepAwakePlugin.swift
  ios/PluginTests/KeepAwakePluginTests.swift
  ios/Podfile.lock
  package-lock.json
  package.json
  src/definitions.ts
  src/index.ts
  src/web.ts
Labels: refactor

#9 refactor(web)!: throw unimplemented error
  src/web.ts
Labels: breaking change, platform: web, refactor

#10 chore(deps-dev): install standard-version
  package-lock.json
  package.json
Labels: dependencies

#14 feat: add `web` support
  README.md
  package-lock.json
  package.json
  src/definitions.ts
  src/web.ts
Labels: feature, platform: web

#15 ci: use nodejs 14
  .github/workflows/ci.yml
Labels: ci
